"""initial schema

All core tables. Enum columns are VARCHAR + one explicit ck_<table>_<enum> CHECK each;
autogenerate emitted duplicate checks, which were removed by hand.

Revision ID: ce5bd7a4c160
Revises:
Create Date: 2026-09-30 12:54:30.653902

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "ce5bd7a4c160"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cve_cache",
        sa.Column("cve_id", sa.String(length=32), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("cvss_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("cve_id", name=op.f("pk_cve_cache")),
    )
    op.create_table(
        "targets",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "target_type",
            sa.Enum(
                "url",
                "ip",
                "domain",
                "repo",
                name="targettype",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("value", sa.String(length=2048), nullable=False),
        sa.Column("data_types", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "data_types <@ ARRAY['general', 'personal', 'payment_card', 'health', 'credentials']::varchar[]",
            name=op.f("ck_targets_data_types_valid"),
        ),
        sa.CheckConstraint(
            "target_type IN ('url', 'ip', 'domain', 'repo')", name=op.f("ck_targets_targettype")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_targets")),
    )
    op.create_table(
        "ownership_verifications",
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "method",
            sa.Enum(
                "dns_txt",
                "http_token",
                "lab",
                name="verificationmethod",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("token", sa.String(length=128), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "verified",
                "expired",
                "failed",
                name="verificationstatus",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "method IN ('dns_txt', 'http_token', 'lab')",
            name=op.f("ck_ownership_verifications_verificationmethod"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'verified', 'expired', 'failed')",
            name=op.f("ck_ownership_verifications_verificationstatus"),
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
            name=op.f("fk_ownership_verifications_target_id_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ownership_verifications")),
        sa.UniqueConstraint("token", name=op.f("uq_ownership_verifications_token")),
    )
    op.create_index(
        op.f("ix_ownership_verifications_target_id"),
        "ownership_verifications",
        ["target_id"],
        unique=False,
    )
    op.create_table(
        "scans",
        sa.Column("target_id", sa.Uuid(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "queued",
                "scanning",
                "analyzing",
                "planning",
                "auditing",
                "reporting",
                "complete",
                "failed",
                name="pipelinestate",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "state IN ('queued', 'scanning', 'analyzing', 'planning', 'auditing', 'reporting', 'complete', 'failed')",
            name=op.f("ck_scans_pipelinestate"),
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["targets.id"],
            name=op.f("fk_scans_target_id_targets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scans")),
    )
    op.create_index(op.f("ix_scans_target_id"), "scans", ["target_id"], unique=False)
    op.create_table(
        "findings",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("evidence", sa.Text(), nullable=True),
        sa.Column("affected_asset", sa.String(length=2048), nullable=False),
        sa.Column("source_scanners", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "info",
                name="severity",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cvss_score", sa.Numeric(precision=3, scale=1), nullable=True),
        sa.Column("cvss_vector", sa.String(length=200), nullable=True),
        sa.Column("cve_ids", sa.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("cwe_ids", sa.ARRAY(sa.String(length=16)), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=True),
        sa.Column("priority", sa.Integer(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'info')",
            name=op.f("ck_findings_severity"),
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_findings_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_findings")),
        sa.UniqueConstraint("scan_id", "fingerprint", name=op.f("uq_findings_scan_id_fingerprint")),
    )
    op.create_index(op.f("ix_findings_scan_id"), "findings", ["scan_id"], unique=False)
    op.create_table(
        "protection_plans",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("spec", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rendered_files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"],
            ["scans.id"],
            name=op.f("fk_protection_plans_scan_id_scans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_protection_plans")),
        sa.UniqueConstraint("scan_id", name=op.f("uq_protection_plans_scan_id")),
    )
    op.create_table(
        "scan_jobs",
        sa.Column("scan_id", sa.Uuid(), nullable=False),
        sa.Column("scanner", sa.String(length=32), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "queued",
                "running",
                "succeeded",
                "failed",
                "timed_out",
                name="jobstatus",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("exit_code", sa.Integer(), nullable=True),
        sa.Column("raw_output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "status IN ('queued', 'running', 'succeeded', 'failed', 'timed_out')",
            name=op.f("ck_scan_jobs_jobstatus"),
        ),
        sa.ForeignKeyConstraint(
            ["scan_id"], ["scans.id"], name=op.f("fk_scan_jobs_scan_id_scans"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scan_jobs")),
    )
    op.create_index(op.f("ix_scan_jobs_scan_id"), "scan_jobs", ["scan_id"], unique=False)
    op.create_table(
        "audit_runs",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("iteration", sa.Integer(), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("summary", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint("iteration BETWEEN 1 AND 5", name=op.f("ck_audit_runs_iteration_range")),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["protection_plans.id"],
            name=op.f("fk_audit_runs_plan_id_protection_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_runs")),
        sa.UniqueConstraint("plan_id", "iteration", name=op.f("uq_audit_runs_plan_id_iteration")),
    )
    op.create_index(op.f("ix_audit_runs_plan_id"), "audit_runs", ["plan_id"], unique=False)
    op.create_table(
        "policy_mappings",
        sa.Column("finding_id", sa.Uuid(), nullable=False),
        sa.Column(
            "framework",
            sa.Enum(
                "owasp_top10",
                "owasp_asvs",
                "nist_800_53",
                "nist_csf",
                "cis",
                "pci_dss",
                "pipeda",
                name="framework",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("control_id", sa.String(length=64), nullable=False),
        sa.Column("control_title", sa.String(length=300), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "framework IN ('owasp_top10', 'owasp_asvs', 'nist_800_53', 'nist_csf', 'cis', 'pci_dss', 'pipeda')",
            name=op.f("ck_policy_mappings_framework"),
        ),
        sa.ForeignKeyConstraint(
            ["finding_id"],
            ["findings.id"],
            name=op.f("fk_policy_mappings_finding_id_findings"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_policy_mappings")),
        sa.UniqueConstraint(
            "finding_id",
            "framework",
            "control_id",
            name=op.f("uq_policy_mappings_finding_id_framework_control_id"),
        ),
    )
    op.create_index(
        op.f("ix_policy_mappings_finding_id"), "policy_mappings", ["finding_id"], unique=False
    )
    op.create_table(
        "audit_findings",
        sa.Column("audit_run_id", sa.Uuid(), nullable=False),
        sa.Column(
            "check",
            sa.Enum(
                "semgrep",
                "bandit",
                "wycheproof",
                "property",
                "llm_review",
                name="auditcheck",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("rule_id", sa.String(length=200), nullable=False),
        sa.Column(
            "severity",
            sa.Enum(
                "critical",
                "high",
                "medium",
                "low",
                "info",
                name="severity",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("location", sa.String(length=500), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "fixed",
                "needs_human_review",
                name="auditfindingstatus",
                native_enum=False,
                create_constraint=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "severity IN ('critical', 'high', 'medium', 'low', 'info')",
            name=op.f("ck_audit_findings_severity"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'fixed', 'needs_human_review')",
            name=op.f("ck_audit_findings_auditfindingstatus"),
        ),
        sa.CheckConstraint(
            "\"check\" IN ('semgrep', 'bandit', 'wycheproof', 'property', 'llm_review')",
            name=op.f("ck_audit_findings_auditcheck"),
        ),
        sa.ForeignKeyConstraint(
            ["audit_run_id"],
            ["audit_runs.id"],
            name=op.f("fk_audit_findings_audit_run_id_audit_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_findings")),
    )
    op.create_index(
        op.f("ix_audit_findings_audit_run_id"), "audit_findings", ["audit_run_id"], unique=False
    )
    op.create_table(
        "patch_logs",
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("audit_run_id", sa.Uuid(), nullable=False),
        sa.Column("audit_finding_id", sa.Uuid(), nullable=True),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("spec_before", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spec_after", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_finding_id"],
            ["audit_findings.id"],
            name=op.f("fk_patch_logs_audit_finding_id_audit_findings"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["audit_run_id"],
            ["audit_runs.id"],
            name=op.f("fk_patch_logs_audit_run_id_audit_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["plan_id"],
            ["protection_plans.id"],
            name=op.f("fk_patch_logs_plan_id_protection_plans"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_patch_logs")),
    )
    op.create_index(
        op.f("ix_patch_logs_audit_run_id"), "patch_logs", ["audit_run_id"], unique=False
    )
    op.create_index(op.f("ix_patch_logs_plan_id"), "patch_logs", ["plan_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_patch_logs_plan_id"), table_name="patch_logs")
    op.drop_index(op.f("ix_patch_logs_audit_run_id"), table_name="patch_logs")
    op.drop_table("patch_logs")
    op.drop_index(op.f("ix_audit_findings_audit_run_id"), table_name="audit_findings")
    op.drop_table("audit_findings")
    op.drop_index(op.f("ix_policy_mappings_finding_id"), table_name="policy_mappings")
    op.drop_table("policy_mappings")
    op.drop_index(op.f("ix_audit_runs_plan_id"), table_name="audit_runs")
    op.drop_table("audit_runs")
    op.drop_index(op.f("ix_scan_jobs_scan_id"), table_name="scan_jobs")
    op.drop_table("scan_jobs")
    op.drop_table("protection_plans")
    op.drop_index(op.f("ix_findings_scan_id"), table_name="findings")
    op.drop_table("findings")
    op.drop_index(op.f("ix_scans_target_id"), table_name="scans")
    op.drop_table("scans")
    op.drop_index(
        op.f("ix_ownership_verifications_target_id"), table_name="ownership_verifications"
    )
    op.drop_table("ownership_verifications")
    op.drop_table("targets")
    op.drop_table("cve_cache")
    # ### end Alembic commands ###
